apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: myapp
spec:
  containers:
    - image: calinrus/hit-counter
      name: myapp
      ports:
        - containerPort: 5000
      resources:
        requests:
          memory: "64Mi"
          cpu: "200m" 
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
      app: myapp
---
apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels:
    app: redis
spec:
  containers:
    - image: redis:3.2-alpine
      name: redis
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-lb
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
      app: redis

